name = "servercardtrust-hotword-pages"
main = "worker/hotwords.js"
compatibility_date = "2026-06-17"
workers_dev = true
routes = [
  { pattern = "servercardtrust.space/*", zone_name = "servercardtrust.space" },
  { pattern = "www.servercardtrust.space/*", zone_name = "servercardtrust.space" }
]

[assets]
directory = "./public-hotwords"
binding = "ASSETS"
run_worker_first = true
